name: Continuous Integration

on:
  - push
  - pull_request

jobs:
  continuous-integration:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-11
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Install GD (macOS)
        run: brew install gd
        if: runner.os == 'macOS'
      - name: Install GD (Linux)
        run: sudo apt install -y libgd-dev
        if: runner.os == 'Linux'
      - name: Test
        run: swift test --enable-test-discovery
      - name: Test (NO_COREGRAPHICS)
        if: runner.os == 'macOS'
        run: swift test --enable-test-discovery -Xswiftc -DNO_COREGRAPHICS
